app:
    resource: '@AppBundle/Controller/'
    type: annotation

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml" 
      
calendar_events:
    path: /json
    defaults: { _controller: AppBundle:Default:loadCalendar }
    options:
        expose: true 

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
